### ISSUE TITLE
Feedback from the cookieMonsters

### ISSUE THREAD

**Issue by Jhdezj** [RaminMammadzada/rails-twitter-redesign#1]
Looking great so far! good job with the use of partials.
These links may be useful for your project:
https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg
https://medium.com/binar-academy/carrierwave-and-cloudinary-for-uploading-images-in-rails-api-ecfee7c5b973

For the deployment of pictures on Heroku you can use Cloudinary

**Comment by RaminMammadzada** [comment]
I have solved it. I choosed Cloudinary as a CDN service and Heroku as a cloud server.
